{% set version = "0.5.41" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-readjdx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/readJDX_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/readJDX/readJDX_{{ version }}.tar.gz
  sha256: 2225d6f1c7b38b15c5cdcd61a3696cefc84d9e69a326ef06dfbcf8c33508c233

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-stringr
  run:
    - r-base
    - r-stringr

test:
  commands:
    - $R -e "library('readJDX')"           # [not win]
    - "\"%R%\" -e \"library('readJDX')\""  # [win]

about:
  home: https://github.com/bryanhanson/readJDX
  license: GPL-3.0-or-later
  summary: Import data written in the JCAMP-DX format. This is an instrument-independent format used in the field of spectroscopy. Examples include IR, NMR, and Raman spectroscopy. See the vignette for background and supported formats.  The official JCAMP-DX site is <http://www.jcamp-dx.org/>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: readJDX
# Type: Package
# Title: Import Data in the JCAMP-DX Format
# Version: 0.4.29
# Date: 2019-11-12
# Authors@R: person( "Bryan A.", "Hanson", role = c("aut", "cre"), email = "hanson@depauw.edu", comment = c(ORCID = "0000-0003-3536-8246"))
# Description: Import data written in the JCAMP-DX format. This is an instrument-independent format used in the field of spectroscopy. Examples include IR, NMR, and Raman spectroscopy. See the vignette for background and supported formats.  The official JCAMP-DX site is <http://www.jcamp-dx.org/>.
# URL: https://github.com/bryanhanson/readJDX
# BugReports: https://github.com/bryanhanson/readJDX/issues
# License: GPL (>= 3)
# ByteCompile: TRUE
# Depends: R (>= 3.0)
# Suggests: knitr, kableExtra, pinp
# Imports: stringr
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-11-12 17:21:41 UTC; bryanhanson
# Author: Bryan A. Hanson [aut, cre] (<https://orcid.org/0000-0003-3536-8246>)
# Maintainer: Bryan A. Hanson <hanson@depauw.edu>
# Repository: CRAN
# Date/Publication: 2019-11-12 18:30:02 UTC
